
[terminal]
vt = 1

[default_session]
command = "tuigreet --remember --cmd startx --theme border=magenta;text=cyan;prompt=green;time=red;action=blue;button=yellow;container=black;input=red"
user = "greeter"
